version: "3.8"

services:
  postgres_test:
    container_name: db_test
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
